### ISSUE TITLE
`update_existing` does not work together with `earch_existing: all`

### ISSUE THREAD

**Issue by tsiegleauq** [JasonEtco/create-an-issue#121]
while "update_existing: true" will work, combining it with "search_existing: all" will not modifiy an old issue, but open a new one.

```yml
- name: Create Issue if models.yml was changed
  uses: JasonEtco/create-an-issue@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ISSUE_TITLE: Something happened
  with:
    filename: .github/workflows/some.md
    update_existing: true
    search_existing: all
```
would not update (an open) issue, while

```yml
- name: Create Issue if models.yml was changed
  uses: JasonEtco/create-an-issue@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ISSUE_TITLE: Something happened
  with:
    filename: .github/workflows/some.md
    update_existing: true
```
will
