### ISSUE TITLE
How can I reopen existing issue?

### ISSUE THREAD

**Issue by CAMOBAP** [JasonEtco/create-an-issue#162]
Thanks for the awesome GitHub Action

Here is my workflow https://github.com/metanorma/ci/blob/main/.github/workflows/ci-repo-watcher.yml

```
...
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || secrets.token }}
      with:
        assignees: CAMOBAP
        update_existing: true
        search_existing: all
        filename: .github/templates/new-repos.md
...
```

Is it possible to change state of `closed` issue to `open`?
