### ISSUE TITLE
Template file cannot be found in my project's workspace

### ISSUE THREAD

**Issue by colin-oos** [JasonEtco/create-an-issue#169]
I am getting the following error:

![image](https://github.com/JasonEtco/create-an-issue/assets/46458035/308eefdf-463c-4588-8f77-651c5f54cdb7)

My template file is located at `.github/downstream-conflict-issue-template.md` and has the following contents:

```
---
title: Resolve PR for tenant {{ env.TENANT }}
labels: downstream conflict
---
There was a merge conflict when updating the downstream repository at http://github.com/{{ env.TENANT }}/{{ env.REPO }}

A [pull request]({{ env.PR_URL }}) was subsequently created which must be resolved at {{ env.PR_URL }}
```

I am using this step like this:

```
- name: Create Issue for ${{ steps.script.outputs.pr_url }}
        if: ${{ steps.script.outputs.has_pr == 'true' }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ steps.script.outputs.pr_url }}
          TENANT: ${{ matrix.tenant }}
          REPO: ${{ env.INPUT_REPO }}
          STAGE: ${{ env.STAGE }}
        with:
          assignees: colin-oos
          filename: .github/downstream-conflict-issue-template.md
```

What am I missing?
