### ISSUE TITLE
HttpError: Validation Failed

### ISSUE THREAD

**Issue by tenhobi** [JasonEtco/create-an-issue#41]
Hi,

when adding multiple assignees, or 1 assignee that is not me, this error occurs:

![image](https://user-images.githubusercontent.com/5287596/74685471-f7291900-51ce-11ea-988c-350b94066446.png)

Any idea how to fix that?

I have this workflow

```
name: docs

on:
  pull_request:
    types:
    - closed
    paths:
    - 'README.md'
    - 'docs/*'

jobs:
  # Create an issue, if any changes to source docs were made.
  create-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2

      - uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/DOCS_ISSUE_TEMPLATE.md
```

and this template:

```
---
title: "[Translations] Include changes from #{{ payload.pull_request.number }}"
assignees: felangel
labels: documentation, translation
---
Update Translations to include #{{ payload.pull_request.number }}

- [ ] en (@felangel)
- [ ] cs (@tenhobi)
```
