### ISSUE TITLE
Allow passing milestone to issue

### ISSUE THREAD

**Issue by bengry** [JasonEtco/create-an-issue#43]
I want to automatically create an issue once a milestone is created, I have the following workflow:
```yml
...
- name: create release-driving issue
  uses: JasonEtco/create-an-issue@v2.2.0
  with:
    filename: .github/issue_templates/RELEASE_ISSUE_TEMPLATE.md
    assignees: ${{ github.actor }}
    milestone: ${{ github.event.milestone.number }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

with `RELEASE_ISSUE_TEMPLATE.md` having the following content:
```md
---
title: ...
labels: release
milestone: {{ tools.inputs.milestone }}
---
```

This doesn't work, and I get the following error when running the workflow:
> ✖  error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/issue_templates/RELEASE_ISSUE_TEMPLATE.md!
✖  error     HttpError: Invalid value for parameter 'milestone': {"[object Object]":null} is NaN 

I guess this is because the template is not being passed the milestone input, even though it seems like it should work, following https://github.com/JasonEtco/actions-toolkit#toolsinputs
