### ISSUE TITLE
issue template frontmatter: can not read a block mapping entry (assignees)

### ISSUE THREAD

**Issue by meowsbits** [JasonEtco/create-an-issue#49]
__.github/workflows/ci.yml__
```yml
    - name: HandleIfFailure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/issue-on-failure.md
```

ISSUE.md contains the frontmatter (taken from examle on the README): https://github.com/JasonEtco/create-an-issue#usage

```yml
---
title: {{ action }} Failed
assignees: meowsbits, belfordz, shanejonas, chunfuyang, tzdybal
labels: bug
---
```
```
Run JasonEtco/create-an-issue@v2
/usr/bin/docker run --name e87b52c88190669f0e4c348eaa15216b31645b_20d9c1 --label e87b52 --workdir /github/workspace --rm -e ETH_DNS_DISCV4_CRAWLTIME -e ETH_DNS_DISCV4_PARENT_DOMAIN -e ETH_DNS_DISCV4_KEY_PATH -e ETH_DNS_DISCV4_KEYPASS_PATH -e CLOUDFLARE_API_TOKEN -e ETH_DNS_CLOUDFLARE_ZONEID -e ETH_DNS_DISCV4_KEY -e ETH_DNS_DISCV4_KEYPASS -e GOROOT -e GITHUB_TOKEN -e INPUT_FILENAME -e INPUT_ASSIGNEES -e INPUT_MILESTONE -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/discv4-dns-lists/discv4-dns-lists":"/github/workspace" e87b52:c88190669f0e4c348eaa15216b31645b
⬤  debug     Reading from file .github/issue-on-failure.md
##[error]can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 10:
    assignees: meowsbits, belfordz, shanejona ... 
             ^
✖  fatal     YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 10: 
    assignees: meowsbits, belfordz, shanejona ... 
             ^
    at generateError (/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/node_modules/js-yaml/lib/js-yaml/loader.js:1073:9)
    at composeNode (/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parse (/node_modules/front-matter/index.js:61:27)
    at extractor (/node_modules/front-matter/index.js:24:12)
    at Toolkit.run (/index.js:28:32)
```
