### ISSUE TITLE
[QUESTION] Why I always have this error ?

### ISSUE THREAD

**Issue by liszto** [JasonEtco/create-an-issue#50]
It didn't work with .github/ISSUE_TEMPLATE.md

so I tried to move it otherway and change the path to a right one.

```
##[error]File issues.md could not be found in your project's workspace.
```

Here is my script. I probably missed a stupid thing but I can't find what...

````
name: Auto-issuing.js CI

on: [push]
 
jobs:
  auto-create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            filename: issues.md
```
