### ISSUE TITLE
env vars dont seem to work

### ISSUE THREAD

**Issue by devkws** [JasonEtco/create-an-issue#60]
I followed your example to use env vars and they dont seem to write to the body or a label

**Comment by JasonEtco** [comment]
Can you share your entire workflow `.yaml` file please?

**Comment by devkws** [comment]
```
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Npm Install
      run: npm install
      
    - name: Npm Test
      run: npm test  
    
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: test1234
```

```
---
title: Deployment needs approval for production
assignees: devkws
labels: needs-approval, {{ env.TAG }}
---

Image to be approved {{ env.TAG }}

```

**Comment by JasonEtco** [comment]
Thanks for including the template file. The `labels` won't work, it isn't targeted by the templating funcitonality:

https://github.com/JasonEtco/create-an-issue/blob/e6b4b190af80961b6462c725454e7828d0247a68/index.js#L32-L35

I'd be open to a PR that adds it, but I elaborate on why that shouldn't be necessary here: https://github.com/JasonEtco/create-an-issue/blob/e6b4b190af80961b6462c725454e7828d0247a68/index.js#L32-L35

For the body - that should be working correctly. This test passes, with the associated snapshot:

https://github.com/JasonEtco/create-an-issue/blob/e6b4b190af80961b6462c725454e7828d0247a68/tests/index.test.js#L72-L78

https://github.com/JasonEtco/create-an-issue/blob/e6b4b190af80961b6462c725454e7828d0247a68/tests/__snapshots__/index.test.js.snap#L137-L140

So I'm not sure what could be causing a problem.

**Comment by devkws** [comment]
the env var just come in as an empty string, very strange. Do you have a sample action you can run to try and reproduce?

![image](https://user-images.githubusercontent.com/22294114/82761812-3d43d900-9dcb-11ea-9f67-3168d265996e.png)

**Comment by JasonEtco** [comment]
I just tried this in a test repo:

```yaml
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXAMPLE: foobar
```

```markdown
---
name: Ecosystem-Events Daily Stand-up Issue
title: Example
labels: standup
---

Hello! {{ env.EXAMPLE }}
```

![image](https://user-images.githubusercontent.com/10660468/82762957-09b87d00-9dd2-11ea-8d1a-c143f6c244d7.png)

---

So it does appear to be working. The only difference I can see is that I'm using `@master` - can you try that temporarily? I'm wondering if that functionality never made it to the `v2` tag.
