### ISSUE TITLE
Inject env.VAR into code block in issue template?

### ISSUE THREAD

**Issue by loosebazooka** [JasonEtco/create-an-issue#81]
I have an issue template that has something like
```
Run `./script.sh {{ env.VERSION }}`
```
and a github action config like:
```
- uses: JasonEtco/create-an-issue@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VERSION: potato
```

but when running the action, `env.VERSION` is never replaced? Is it not possible to replace values in backtick/code blocks? The generated issue just has the uninjected "Run `./script.sh {{ env.VERSION }}`" instead of "Run `./script.sh potato`"
