### ISSUE TITLE
When username and package name are same, GH secret overwrites the package name and put it as ***

### ISSUE THREAD

**Issue by royki** [JasonEtco/create-an-issue#99]
Here is my Makefile to build a docker image - 

```makefile
LIBRARY = ekc-azure-proxy-server
PACKAGE_NAME = energyweb/${LIBRARY}
TAG_LATEST := $(shell rush list --json | jq .projects | jq -r '.[] | select(.name=="@energyweb/${LIBRARY}") | .version')

build-image:
	docker build --force-rm $(options) -t ${PACKAGE_NAME}:${TAG_LATEST} .
```
Here is the [CI Output](https://github.com/energywebfoundation/ekc-monorepo/runs/2932038079?check_suite_focus=true#step:11:1), which is working to build the docker image. (It is private repo, hence I'm pasting the result here)

```console
Successfully tagged energyweb/ekc-azure-proxy-server:0.0.1
```
Which is Nice and expected.

Now, when it's time to publish the image in docker hub. So I created two secret variable in GH Secrets (Actions secrets) as 
`DOCKER_USERNAME` and `DOCKER_PASSWORD`. In this case `DOCKER_USERNAME` is `energyweb`.

GH CI to Publishing Image to docker hub - 
```yaml
 - name: Push to Docker Hub
    uses: docker/build-push-action@v2
    with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       push: true
       tags: energyweb/ekc-azure-proxy-server:${{ steps.TAG_LATEST.output }}
```

From now, all my NPM package name as well as docker image name started coming as `***/ekc-azure-proxy-server:0.0.1`

Here is the Docker build output now .  [CI Output](https://github.com/energywebfoundation/ekc-monorepo/runs/2933934092?check_suite_focus=true#step:11:180)
```console
Successfully tagged ***/ekc-azure-proxy-server:0.0.1
```

It should be `energyweb/ekc-azure-proxy-server:0.0.1`
Same as NPM Packages name it is coming as `***/ekc-azure-proxy-server:0.0.1` 
NPM Package name should also be fully qualified name - `energyweb/ekc-azure-proxy-server:0.0.1`
